service: dry
plugins:
  - serverless-s3-sync
  - serverless-pseudo-parameters
  - "@anttiviljami/serverless-stack-output"

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs8.10
  profile: daniel

custom:
  output:
    # handler: output.handler
    file: .serverless/stack.json
  stage: "${opt:stage, self:provider.stage}"
  prefix: "${self:service}-${self:custom.stage}"
  siteName: "${self:custom.prefix}-site"
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: dist/${self:service}
  cloudfrontInvalidate:
    distributionId: ['Fn::GetAtt': [ SiteCloudFrontDistribution, DomainName ]]
    # distributionIdKey: 'CDNDistributionId' #conditional, distributionId or distributionIdKey is required.
    items: # one or more paths required
      - '/index.html'

resources:
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/site.yml)}

