Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions: ${file(resources/user-entity-table.json):AttributeDefinitions}
      KeySchema: ${file(resources/user-entity-table.json):KeySchema}
      GlobalSecondaryIndexes: ${file(resources/user-entity-table.json):GlobalSecondaryIndexes}
      TableName: ${self:custom.notesTableName}

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: ${self:custom.usersTableName}
      AttributeDefinitions: ${file(resources/entity-table.json):AttributeDefinitions}
      KeySchema: ${file(resources/entity-table.json):KeySchema}

  AnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      TableName: ${self:custom.analysisTableName}
      AttributeDefinitions: ${file(resources/user-entity-table.json):AttributeDefinitions}
      KeySchema: ${file(resources/user-entity-table.json):KeySchema}
      GlobalSecondaryIndexes: ${file(resources/user-entity-table.json):GlobalSecondaryIndexes}

Outputs:
  notesTableName:
    Value: ${self:custom.notesTableName}
  analysisTableName:
    Value: ${self:custom.analysisTableName}
  usersTableName:
    Value: ${self:custom.usersTableName}
